### ISSUE TITLE
call for lightning talk speakers

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#3]
5? 5 minutes?

**Comment by kosamari** [comment]
For our regular BrooklynJS 10min x 5 talks (with no Q&A) every months.
Some other popular meetup like Hack and Tell does 5min talk + 5min Q&A as many as they can fit in.

On Regular months, we don't have any particular therm, in past 19 regular events, we've done "Hardware night" and "Art night" where all 5 talks were in a theme. 

For October this year (since it is close to halloween) an attendees suggested "developer horror story" theme which we might seriously consider.

**Comment by visnup** [comment]
all great ideas for format. I kinda want to start with 3-4x 10min talks and tweak from there. I'm a little nervous about 5x for our inaugural one just because it's a larger number.

ooh, I like "developer horror story". it's like dailywtf but more animated, and everyone has one.

**Comment by kosamari** [comment]
Also each meetup in boro.js fam has unique focus.

Ours is lightning talks. 

Manhattan JS always have one "passion talk" - where people share non-technical project (i.e clear ice making, dancing, hot sauce, analog synth, puns etc)

Queens JS has focus in bringing one Jr dev and one Jr speaker (not alway the same person!) to talk.

Both manhattan and queens go by 3 talks each event.

**Comment by visnup** [comment]
re: jr dev and jr speaker, we were definitely going to post/recruit talk requests from all the dev schools in the area. I like the idea of sticking to lightning talks, and then doing them in themes. so, "passion" as a theme or "first time using" as a theme, etc.

I definitely love the "passion" talks personally. they break the ice on getting to know that person.

**Comment by visnup** [comment]
@contra I know you've been wanting to talk about something non-gulp for a while, right? do you have a 10 minute talk you feel like giving?

**Comment by contra** [comment]
@visnup yeah i have some cool shit i can talk about

**Comment by visnup** [comment]
@contra nice. I'm going to bug you in about a month. also @funkytek, want to do some musical performance?

**Comment by visnup** [comment]
closing in favor of #16.
