### ISSUE TITLE
December Call for Speakers

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#78]
We're looking for speakers for our meetup!

![????](https://media.giphy.com/media/hcZZmrMHsUSNG/giphy.gif)

**How do I submit a talk?**
You can either comment on this issue or [send us an email](mailto:talks@wafflejs.com?subject=Talk Submission).

**When and where will it be?**
When: Wednesday, December 2 from 7 to 10 PM.
Where: [Soma StrEat Food Park](https://www.google.com/maps/place/SoMa+StrEat+Food+Park/@37.769798,-122.412043,17z/data=!3m1!4b1!4m2!3m1!1s0x808f7e28b17fa279:0xcaa79b9fbbc34ee)

**What should I talk about?**
Something you're excited about, outside of work. It doesn't have to be tech-related, but it'd be nice!

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
Just a few sentences describing what you want to talk about would be great.

**What's the A/V situation?**
We'll have a projector and a mic for you to use. Let us know if you need any fancy adapters (we'll have some Apple ones).

**Comment by nebrius** [comment]
I've been ruminating on this idea for a while, and it's finally becoming clear(er).

Title: Learn these 5 simple tricks to become a JavaScript ninja

Summary:

So it's a satirical talk that teaches 5 (or so) pretty absurd things about JavaScript. Things that, in actuality, you probably wish you didn't know. I don't want to spoil any of the fun, but I'll give a hint on one of them: it abuses the `with` statement and the global scope to rather comedic effect :D

I'm still figuring out how to work it in, but I'm planning on incorporating a sort of undercurrent of "Arcane knowledge of languages and frameworks doesn't actually make one exceptional, and the whole ninja/rockstar/etc thing is ridiculous."

**Comment by visnup** [comment]
@nebrius ah crap we never responded to you. I'll add your proposal into our growing spreadsheet of talk ideas. this one slipped through the cracks! 😓

**Comment by nebrius** [comment]
No worries, there's plenty of waffles in the future to combine with speaking :)

**Comment by billyroh** [comment]
@nebrius: For your trouble we just sent you a free ticket. Again, sorry that we never responded to you and we hope to see you at the event!

**Comment by nebrius** [comment]
Got it, and thanks! I'll be there :)

**Comment by ashleygwilliams** [comment]
heyyo- one day i'd like to talk at your meetup! i am from NYC but come to SF a whole bunch, because i work for NPM.

here are some talks i have given and could give at your meetup!
- npm by the numbers (data about how people use npm and what it means for the community) [node interactive keynote]
- you don't know npm (lots of cool features npm has that you might not know about) [seattlejs, microsoft reactor]
- if you wish to learn es6 from scratch you must first invent the universe (carl sagan themed talk about education and programming language design, and es6) [first given at jsconf us, then literally a thousand other places]

if you want to see videos and decks, there are many, and i'm happy to send. lemme know!

**Comment by visnup** [comment]
@ashleygwilliams thanks! When do you think you'll be in town next? Our upcoming dates are Jan 6, Feb 3, and Mar 2.
